version: '3.7'

services:
  server_app:
    build: .
    container_name: server_app
    environment:
      - TZ=${TZ}
      - UID=${UID}
      - GID=${GID}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./config.ini:/app/config.ini
      - ./logs:/app/logs
    ports:
      - "1234:1234"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1234/health"]
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 5s

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 5s

volumes:
  postgres_data:
