version: '3.8'

services:
  client_app:
    build: .
    container_name: client_app
    environment:
      - TZ=${TZ}
      - UID=${UID}
      - GID=${GID}
    ports:
      - "1234:1234"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1234/health"]
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 5s
  
